[package]
name = "bs3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.9.0"
hex = { version = "0.4", default-features = false, features = ["alloc"]}
serde = { version = "1.0", features = ["derive", "alloc"], default-features = false }
log = "0.4.14"
serde_cbor = { version = "0.11", default-features = false, features = ["alloc"], optional = true }

# dependency for seld.
sled = { version = "0.34", optional = true }

[features]
default = ["cbor"]

# feature for std usage.
std = []
nightly = []

# Define backend.
sled-backend = ["sled", "std"]

cbor = ["serde_cbor"]
