[package]
name = "bs3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = { version = "0.34", optional = true }
digest = "0.9.0"

[features]
sled-backend = ["sled"]
